#!/usr/bin/env bash
# Runs INSIDE the builder container (archlinux:base-devel). Invoked by
# build-iso.sh with BASE_REPO and BASE_COMMIT in the environment.
# Flow: deps -> keyring -> clone pinned CachyOS-Live-ISO -> apply AstroOS
# delta -> run THEIR buildiso.sh -> collect artifacts to /build/out.
set -euo pipefail

: "${BASE_REPO:?}" "${BASE_COMMIT:?}"

ulimit -n 1048576 || true
echo ">> nofile limit: $(ulimit -n)"

# The image default mirror throttles big transactions; pin geo + fallbacks.
printf '%s\n' \
  'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' \
  'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' \
  'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' \
  > /etc/pacman.d/mirrorlist

pacman -Syu --noconfirm --needed base-devel archiso mkinitcpio-archiso git \
  squashfs-tools grub syslinux

# Keyring: Arch packager keys + the CachyOS signing key (the base profile's
# pacman.conf enables [cachyos] with SigLevel Required).
pacman-key --init
pacman-key --populate archlinux
# Keyservers flake ("keyserver receive failed: No data"), so: retry across
# transports, then fall back to extracting the key from the cachyos-keyring
# package over https from their mirror.
import_cachyos_key() {
  local ks try
  for ks in hkps://keyserver.ubuntu.com hkp://keyserver.ubuntu.com:80; do
    for try in 1 2 3; do
      pacman-key --recv-keys F3B607488DB35A47 --keyserver "$ks" && return 0
      sleep 5
    done
  done
  echo ">> Keyservers unreachable; extracting key from cachyos-keyring package"
  local idx pkg
  idx=$(curl -sL https://mirror.cachyos.org/repo/x86_64/cachyos/)
  pkg=$(printf '%s' "$idx" | grep -oE 'cachyos-keyring-[0-9][^"<>]*\.pkg\.tar\.zst' | head -1)
  [[ -n "$pkg" ]] || { echo "!! cachyos-keyring package not found in mirror index" >&2; return 1; }
  curl -sLo /tmp/cachyos-keyring.zst "https://mirror.cachyos.org/repo/x86_64/cachyos/$pkg"
  bsdtar -xf /tmp/cachyos-keyring.zst -C /tmp 'usr/share/pacman/keyrings/*'
  pacman-key --add /tmp/usr/share/pacman/keyrings/cachyos.gpg
}
import_cachyos_key
pacman-key --lsign-key F3B607488DB35A47
# Mass verification in a container dies mid-transaction with
# "GPGME error: Inappropriate ioctl for device" when gpg decides it wants a
# tty. Belt (no-tty here) and suspenders (-t on the podman run).
printf 'no-tty\n' >> /etc/pacman.d/gnupg/gpg.conf

# Base: pinned CachyOS-Live-ISO checkout (fresh each build).
base=/build/work/base
rm -rf "$base"
mkdir -p /build/work /build/out
git clone --quiet "$BASE_REPO" "$base"
git -C "$base" checkout --quiet "$BASE_COMMIT"
echo ">> base: CachyOS-Live-ISO @ $(git -C "$base" rev-parse --short HEAD)"

prof="$base/archiso"

# --- AstroOS delta 1: packages -------------------------------------------
# Append our additions to the desktop list (their prepare_profile copies
# packages_desktop.x86_64 -> packages.x86_64), deduped against the base set.
grep -vE '^\s*(#|$)' /build/astroos/astroos-additions.x86_64 | sort -u > /tmp/astro.add
grep -vE '^\s*(#|$)' "$prof/packages_desktop.x86_64" | sort -u > /tmp/astro.base
{
  echo ''
  echo '# --- AstroOS additions (astroos/astroos-additions.x86_64) ---'
  comm -23 /tmp/astro.add /tmp/astro.base
} >> "$prof/packages_desktop.x86_64"
net_adds=$(comm -23 /tmp/astro.add /tmp/astro.base | wc -l)
echo ">> package list: $(grep -cvE '^\s*(#|$)' "$prof/packages_desktop.x86_64") total ($net_adds AstroOS additions)"
# Council R2 (B2): a suspiciously small additions count means the generated
# list is broken (e.g. gen-packages emitting garbage) — a base-only ISO would
# still pass the boot gate, so fail here instead of shipping a no-op AstroOS.
min_adds="${ASTROOS_MIN_ADDITIONS:-80}"
if (( net_adds < min_adds )); then
  echo "!! Only $net_adds net additions (< $min_adds floor) — additions list looks broken. Aborting." >&2
  exit 1
fi

# --- AstroOS delta 2: airootfs overlay -----------------------------------
cp -a /build/astroos/overlay/airootfs/. "$prof/airootfs/"
# --- AstroOS delta 2b: branding (assets generated by branding/assetgen.py) --
br=/build/astroos/branding/out
for s in 512 256 128 64 48 32 16; do
  install -Dm644 "$br/icons/${s}x${s}/astroos-logo.png" \
    "$prof/airootfs/usr/share/icons/hicolor/${s}x${s}/apps/astroos-logo.png"
done
install -Dm644 "$br/astroos-logo.png" "$prof/airootfs/usr/share/pixmaps/astroos-logo.png"
install -Dm644 "$br/astroos-wallpaper.png" \
  "$prof/airootfs/usr/share/wallpapers/AstroOS/contents/images/3840x2160.png"
install -Dm644 "$br/astroos-logo.ansi" "$prof/airootfs/etc/fastfetch/astroos-logo.ansi"
# plymouth owns usr/share/plymouth/themes/spinner/watermark.png, and mkarchiso
# copies the profile airootfs BEFORE pacstrap — pre-placing the branded file is
# a fatal pacman file conflict (builds 11-12; NoExtract does NOT exempt a path
# from the conflict check). Stage it at an AstroOS-owned path and let an alpm
# PostTransaction hook copy it over plymouth's. The hook also re-brands after
# every future plymouth upgrade on installed systems. Numbered 85 so it runs
# before 90-mkinitcpio-install and the branded file lands in the initramfs.
install -Dm644 "$br/watermark.png" \
  "$prof/airootfs/usr/share/astroos/branding/watermark.png"
mkdir -p "$prof/airootfs/etc/pacman.d/hooks"
cat > "$prof/airootfs/etc/pacman.d/hooks/85-astroos-plymouth-watermark.hook" <<'HOOK'
[Trigger]
Operation = Install
Operation = Upgrade
Type = Path
Target = usr/share/plymouth/themes/spinner/watermark.png

[Action]
Description = AstroOS: re-brand plymouth spinner watermark
When = PostTransaction
Exec = /usr/bin/cp /usr/share/astroos/branding/watermark.png /usr/share/plymouth/themes/spinner/watermark.png
HOOK
# Mask CachyOS's identity-writing hooks (build 13: their cachyos-branding
# script rewrote os-release/lsb-release to CachyOS after our overlay landed).
# A same-name file in /etc/pacman.d/hooks overrides /usr/share/libalpm/hooks;
# a /dev/null symlink disables the hook. The overlay's zz-astroos-identity.hook
# then asserts AstroOS identity as the last hook in every transaction.
for h in cachyos-branding.hook lsb-release.hook; do
  ln -sf /dev/null "$prof/airootfs/etc/pacman.d/hooks/$h"
done
# Bootloader splashes + menu titles. Only the capitalized brand string is
# rewritten: lowercase "cachyos" appears in kernel and package file paths
# (vmlinuz-linux-cachyos) and must never be touched.
install -m644 "$br/splash-1920.png" "$base/archiso/grub/splash.png"
install -m644 "$br/splash-1920.png" "$base/archiso/syslinux/splash.png"
install -m644 "$br/splash-640.png"  "$base/archiso/syslinux/splash1.png"
sed -i 's/CachyOS/AstroOS/g' "$base/archiso/grub/grub.cfg" \
  "$base/archiso/grub/loopback.cfg" "$base"/archiso/syslinux/*.cfg

# --- AstroOS delta 2c: [astroos] prebuilt AUR repo (council R3, ratified) --
# Gated: flips on once the repo is published + verified. Adds the signed
# Azure-hosted repo to the build AND the shipped system, trusts the key, and
# installs the 26 aur.list packages from prebuilt binaries.
if [[ "${ASTROOS_WITH_AUR_REPO:-0}" == "1" ]]; then
  akr=/build/astroos/overlay/airootfs/usr/share/pacman/keyrings
  fpr_expect=$(tr -d ' \r\n' < /build/astroos/branding/REPO_FINGERPRINT)
  # Q2 fingerprint assertion: shipped keyring must be the key the repo db is
  # signed with.
  fpr_ship=$(gpg --show-keys --with-colons "$akr/astroos.gpg" | awk -F: '/^fpr/{print $10; exit}')
  [[ "$fpr_ship" == "$fpr_expect" ]] \
    || { echo "!! astroos keyring fingerprint mismatch: shipped=$fpr_ship expected=$fpr_expect" >&2; exit 1; }
  pacman-key --add "$akr/astroos.gpg"
  pacman-key --lsign-key "$fpr_expect"
  repo_url='https://astroosrepo.blob.core.windows.net/repo/astroos/$arch'
  # D4 client-side machine check: repo db name set == aur.list scope, BEFORE
  # pacstrap. A missing/extra name means repo and tree diverged — hard fail.
  mapfile -t aur_scope < <(tr -d '\r' < /build/astroos/meta/aur.list | grep -vE '^\s*(#|$)' | awk '{print $1}' | sort)
  curl -sfL "https://astroosrepo.blob.core.windows.net/repo/astroos/x86_64/astroos.db.tar.zst" -o /tmp/astroos.db.tar.zst \
    || { echo "!! [astroos] repo db unreachable" >&2; exit 1; }
  mapfile -t db_names < <(bsdtar -tf /tmp/astroos.db.tar.zst | awk -F/ 'NF>1 && $2==""{print $1}' | sed 's/-[^-]*-[^-]*$//' | sort -u)
  if [[ "$(printf '%s\n' "${aur_scope[@]}")" != "$(printf '%s\n' "${db_names[@]}")" ]]; then
    echo "!! [astroos] repo/tree scope mismatch (D4):" >&2
    diff <(printf '%s\n' "${aur_scope[@]}") <(printf '%s\n' "${db_names[@]}") >&2 || true
    exit 1
  fi
  echo ">> [astroos] repo check OK: ${#db_names[@]} packages match aur.list scope"
  # Repo section for the BUILD (pacstrap pulls prebuilt binaries) and for the
  # SHIPPED system (live ISO + what the installer copies). SigLevel staging
  # per R3 D2/Q4: Required DatabaseOptional for publish cycle 1 only.
  repo_section=$(printf '\n[astroos]\nSigLevel = Required DatabaseOptional\nServer = %s\n' "$repo_url")
  awk -v s="$repo_section" '/^\[cachyos\]/ && !done {print s; done=1} {print}' \
    "$prof/pacman.conf" > /tmp/pconf && mv /tmp/pconf "$prof/pacman.conf"
  awk -v s="$repo_section" '/^\[cachyos\]/ && !done {print s; done=1} {print}' \
    "$prof/airootfs/etc/pacman.conf" > /tmp/pconf2 && mv /tmp/pconf2 "$prof/airootfs/etc/pacman.conf"
  grep -q '^\[astroos\]' "$prof/pacman.conf" || { echo "!! [astroos] section not inserted (no [cachyos] anchor?)" >&2; exit 1; }
  # The 26 AUR-lane packages ride the normal additions path now.
  printf '%s\n' "${aur_scope[@]}" >> "$prof/packages_desktop.x86_64"
  echo ">> [astroos] enabled: +${#aur_scope[@]} prebuilt AUR packages"
fi

# Overlay integrity preflight (council R2, D4). The mask units live in git as
# symlink blobs that a Windows worktree cannot materialize — a checkout that
# silently loses them still builds and boots, so assert them here.
preflight_fail=0
for u in systemd-networkd-wait-online.service systemd-time-wait-sync.service; do
  p="$prof/airootfs/etc/systemd/system/$u"
  [[ -L "$p" && "$(readlink "$p")" == "/dev/null" ]] \
    || { echo "!! overlay preflight: $u is not a /dev/null mask symlink" >&2; preflight_fail=1; }
done
for f in usr/local/bin/astroos-doctor usr/local/bin/astroos-smoke-report \
         usr/local/bin/astroos-cuda-setup etc/systemd/system/astroos-smoke.service \
         etc/os-release etc/fastfetch/astroos-logo.ansi \
         usr/share/wallpapers/AstroOS/contents/images/3840x2160.png \
         usr/share/pixmaps/astroos-logo.png \
         usr/share/astroos/branding/watermark.png \
         usr/share/astroos/branding/os-release \
         usr/share/astroos/branding/lsb-release \
         etc/pacman.d/hooks/85-astroos-plymouth-watermark.hook \
         etc/pacman.d/hooks/zz-astroos-identity.hook; do
  [[ -e "$prof/airootfs/$f" ]] \
    || { echo "!! overlay preflight: missing $f" >&2; preflight_fail=1; }
done
[[ -L "$prof/airootfs/etc/systemd/system/multi-user.target.wants/astroos-smoke.service" ]] \
  || { echo "!! overlay preflight: smoke unit wants-symlink missing" >&2; preflight_fail=1; }
for h in cachyos-branding.hook lsb-release.hook; do
  p="$prof/airootfs/etc/pacman.d/hooks/$h"
  [[ -L "$p" && "$(readlink "$p")" == "/dev/null" ]] \
    || { echo "!! overlay preflight: pacman hook mask $h missing" >&2; preflight_fail=1; }
done
(( preflight_fail == 0 )) || exit 1
echo ">> overlay preflight OK"

# --- AstroOS delta 3: identity -------------------------------------------
sed -i 's/^iso_name=.*/iso_name="astroos"/' "$prof/profiledef.sh"
sed -i 's/^iso_label=.*/iso_label="ASTROOS$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%y%m)"/' "$prof/profiledef.sh"
sed -i 's|^iso_publisher=.*|iso_publisher="AstroOS <https://github.com/bakathefish>"|' "$prof/profiledef.sh"
# Exec bits inside the image are governed by profiledef file_permissions;
# register our overlay executables there (build 8 shipped doctor 0644).
sed -i 's|^file_permissions=(|file_permissions=(\n  ["/usr/local/bin/astroos-doctor"]="0:0:755"\n  ["/usr/local/bin/astroos-smoke-report"]="0:0:755"\n  ["/usr/local/bin/astroos-cuda-setup"]="0:0:755"|' "$prof/profiledef.sh"

# --- Iteration mode -------------------------------------------------------
# ASTROOS_FAST=1 swaps squashfs xz (slow, small; the release setting) for
# zstd (minutes instead of hours). Boot behavior is identical; release
# builds run without the flag.
if [[ "${ASTROOS_FAST:-0}" == "1" ]]; then
  echo ">> FAST build: squashfs zstd instead of xz"
  sed -i "s/^airootfs_image_tool_options=.*/airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '6' '-b' '1M')/" \
    "$prof/profiledef.sh"
fi

# --- Their build (three one-line patches) --------------------------------
# Their buildiso.sh traps EXIT itself with an error message, so EVERY run —
# success included — ends with "==> ERROR: An unknown error has occurred."
# (ledger R2-C3). Delete only the EXIT trap; ERR/INT/TERM traps stay intact.
sed -i "/trap 'trap_exit EXIT/d" "$base/buildiso.sh"
# USER: their util-iso.sh ends with `sudo chown $USER $outFolder`; in the
# container's non-login root shell $USER is unset and the chown (after the
# ISO is fully written) errors out the whole script.
export USER=root
# Their post-build rename hardcodes the "cachyos" filename prefix in two
# places; with our iso_name=astroos the mv can't find its source.
sed -i 's|/cachyos-$(date|/astroos-$(date|' "$base/util-iso.sh"
sed -i 's|vars+=("cachyos")|vars+=("astroos")|' "$base/util-iso.sh"
cd "$base"
./buildiso.sh -p desktop

# --- Collect artifacts ----------------------------------------------------
iso=$(find "$base/out" -name '*.iso' -printf '%f\n' | head -1)
[[ -n "$iso" ]] || { echo "!! No ISO produced" >&2; exit 1; }
mv "$(find "$base/out" -name '*.iso' | head -1)" /build/out/
cp "$prof/packages_desktop.x86_64" /build/out/manifest.pkglist
echo ">> ISO: /build/out/$iso"
