#!/usr/bin/env bash
# Runs INSIDE the builder container (archlinux:base-devel). Invoked by
# build-iso.sh with BASE_REPO and BASE_COMMIT in the environment.
# Flow: deps -> keyring -> clone pinned CachyOS-Live-ISO -> apply AstroOS
# delta -> run THEIR buildiso.sh -> collect artifacts to /build/out.
set -euo pipefail

: "${BASE_REPO:?}" "${BASE_COMMIT:?}"

ulimit -n 1048576 || true
echo ">> nofile limit: $(ulimit -n)"

# The image default mirror throttles big transactions; pin geo + fallbacks.
printf '%s\n' \
  'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' \
  'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' \
  'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' \
  > /etc/pacman.d/mirrorlist

pacman -Syu --noconfirm --needed base-devel archiso mkinitcpio-archiso git \
  squashfs-tools grub syslinux

# Keyring: Arch packager keys + the CachyOS signing key (the base profile's
# pacman.conf enables [cachyos] with SigLevel Required).
pacman-key --init
pacman-key --populate archlinux
# Keyservers flake ("keyserver receive failed: No data"), so: retry across
# transports, then fall back to extracting the key from the cachyos-keyring
# package over https from their mirror.
import_cachyos_key() {
  local ks try
  for ks in hkps://keyserver.ubuntu.com hkp://keyserver.ubuntu.com:80; do
    for try in 1 2 3; do
      pacman-key --recv-keys F3B607488DB35A47 --keyserver "$ks" && return 0
      sleep 5
    done
  done
  echo ">> Keyservers unreachable; extracting key from cachyos-keyring package"
  local idx pkg
  idx=$(curl -sL https://mirror.cachyos.org/repo/x86_64/cachyos/)
  pkg=$(printf '%s' "$idx" | grep -oE 'cachyos-keyring-[0-9][^"<>]*\.pkg\.tar\.zst' | head -1)
  [[ -n "$pkg" ]] || { echo "!! cachyos-keyring package not found in mirror index" >&2; return 1; }
  curl -sLo /tmp/cachyos-keyring.zst "https://mirror.cachyos.org/repo/x86_64/cachyos/$pkg"
  bsdtar -xf /tmp/cachyos-keyring.zst -C /tmp 'usr/share/pacman/keyrings/*'
  pacman-key --add /tmp/usr/share/pacman/keyrings/cachyos.gpg
}
import_cachyos_key
pacman-key --lsign-key F3B607488DB35A47
# Mass verification in a container dies mid-transaction with
# "GPGME error: Inappropriate ioctl for device" when gpg decides it wants a
# tty. Belt (no-tty here) and suspenders (-t on the podman run).
printf 'no-tty\n' >> /etc/pacman.d/gnupg/gpg.conf

# Base: pinned CachyOS-Live-ISO checkout (fresh each build).
base=/build/work/base
rm -rf "$base"
mkdir -p /build/work /build/out
git clone --quiet "$BASE_REPO" "$base"
git -C "$base" checkout --quiet "$BASE_COMMIT"
echo ">> base: CachyOS-Live-ISO @ $(git -C "$base" rev-parse --short HEAD)"

prof="$base/archiso"

# --- AstroOS delta 1: packages -------------------------------------------
# Append our additions to the desktop list (their prepare_profile copies
# packages_desktop.x86_64 -> packages.x86_64), deduped against the base set.
grep -vE '^\s*(#|$)' /build/astroos/astroos-additions.x86_64 | sort -u > /tmp/astro.add
grep -vE '^\s*(#|$)' "$prof/packages_desktop.x86_64" | sort -u > /tmp/astro.base
{
  echo ''
  echo '# --- AstroOS additions (astroos/astroos-additions.x86_64) ---'
  comm -23 /tmp/astro.add /tmp/astro.base
} >> "$prof/packages_desktop.x86_64"
net_adds=$(comm -23 /tmp/astro.add /tmp/astro.base | wc -l)
echo ">> package list: $(grep -cvE '^\s*(#|$)' "$prof/packages_desktop.x86_64") total ($net_adds AstroOS additions)"
# Council R2 (B2): a suspiciously small additions count means the generated
# list is broken (e.g. gen-packages emitting garbage) — a base-only ISO would
# still pass the boot gate, so fail here instead of shipping a no-op AstroOS.
min_adds="${ASTROOS_MIN_ADDITIONS:-80}"
if (( net_adds < min_adds )); then
  echo "!! Only $net_adds net additions (< $min_adds floor) — additions list looks broken. Aborting." >&2
  exit 1
fi

# --- AstroOS delta 2: airootfs overlay -----------------------------------
cp -a /build/astroos/overlay/airootfs/. "$prof/airootfs/"
# --- AstroOS delta 2b: branding (assets generated by branding/assetgen.py) --
br=/build/astroos/branding/out
for s in 512 256 128 64 48 32 16; do
  install -Dm644 "$br/icons/${s}x${s}/astroos-logo.png" \
    "$prof/airootfs/usr/share/icons/hicolor/${s}x${s}/apps/astroos-logo.png"
done
install -Dm644 "$br/astroos-logo.png" "$prof/airootfs/usr/share/pixmaps/astroos-logo.png"
install -Dm644 "$br/astroos-wallpaper.png" \
  "$prof/airootfs/usr/share/wallpapers/AstroOS/contents/images/3840x2160.png"
install -Dm644 "$br/astroos-logo.ansi" "$prof/airootfs/etc/fastfetch/astroos-logo.ansi"
install -Dm644 "$br/watermark.png" \
  "$prof/airootfs/usr/share/plymouth/themes/spinner/watermark.png"
# plymouth ships its own spinner watermark, and mkarchiso copies the profile
# airootfs BEFORE pacstrap — the pre-placed branded file is a fatal pacman file
# conflict (build 11). NoExtract makes pacman skip the package's copy so ours
# survives. Installed systems get the real fix via the branding package fork.
sed -i '/^\[options\]/a NoExtract   = usr/share/plymouth/themes/spinner/watermark.png' \
  "$prof/pacman.conf"
# Bootloader splashes + menu titles. Only the capitalized brand string is
# rewritten: lowercase "cachyos" appears in kernel and package file paths
# (vmlinuz-linux-cachyos) and must never be touched.
install -m644 "$br/splash-1920.png" "$base/archiso/grub/splash.png"
install -m644 "$br/splash-1920.png" "$base/archiso/syslinux/splash.png"
install -m644 "$br/splash-640.png"  "$base/archiso/syslinux/splash1.png"
sed -i 's/CachyOS/AstroOS/g' "$base/archiso/grub/grub.cfg" \
  "$base/archiso/grub/loopback.cfg" "$base"/archiso/syslinux/*.cfg

# Overlay integrity preflight (council R2, D4). The mask units live in git as
# symlink blobs that a Windows worktree cannot materialize — a checkout that
# silently loses them still builds and boots, so assert them here.
preflight_fail=0
for u in systemd-networkd-wait-online.service systemd-time-wait-sync.service; do
  p="$prof/airootfs/etc/systemd/system/$u"
  [[ -L "$p" && "$(readlink "$p")" == "/dev/null" ]] \
    || { echo "!! overlay preflight: $u is not a /dev/null mask symlink" >&2; preflight_fail=1; }
done
for f in usr/local/bin/astroos-doctor usr/local/bin/astroos-smoke-report \
         usr/local/bin/astroos-cuda-setup etc/systemd/system/astroos-smoke.service \
         etc/os-release etc/fastfetch/astroos-logo.ansi \
         usr/share/wallpapers/AstroOS/contents/images/3840x2160.png \
         usr/share/pixmaps/astroos-logo.png; do
  [[ -e "$prof/airootfs/$f" ]] \
    || { echo "!! overlay preflight: missing $f" >&2; preflight_fail=1; }
done
[[ -L "$prof/airootfs/etc/systemd/system/multi-user.target.wants/astroos-smoke.service" ]] \
  || { echo "!! overlay preflight: smoke unit wants-symlink missing" >&2; preflight_fail=1; }
(( preflight_fail == 0 )) || exit 1
echo ">> overlay preflight OK"

# --- AstroOS delta 3: identity -------------------------------------------
sed -i 's/^iso_name=.*/iso_name="astroos"/' "$prof/profiledef.sh"
sed -i 's/^iso_label=.*/iso_label="ASTROOS$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%y%m)"/' "$prof/profiledef.sh"
sed -i 's|^iso_publisher=.*|iso_publisher="AstroOS <https://github.com/bakathefish>"|' "$prof/profiledef.sh"
# Exec bits inside the image are governed by profiledef file_permissions;
# register our overlay executables there (build 8 shipped doctor 0644).
sed -i 's|^file_permissions=(|file_permissions=(\n  ["/usr/local/bin/astroos-doctor"]="0:0:755"\n  ["/usr/local/bin/astroos-smoke-report"]="0:0:755"\n  ["/usr/local/bin/astroos-cuda-setup"]="0:0:755"|' "$prof/profiledef.sh"

# --- Iteration mode -------------------------------------------------------
# ASTROOS_FAST=1 swaps squashfs xz (slow, small; the release setting) for
# zstd (minutes instead of hours). Boot behavior is identical; release
# builds run without the flag.
if [[ "${ASTROOS_FAST:-0}" == "1" ]]; then
  echo ">> FAST build: squashfs zstd instead of xz"
  sed -i "s/^airootfs_image_tool_options=.*/airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '6' '-b' '1M')/" \
    "$prof/profiledef.sh"
fi

# --- Their build (two one-line patches) ----------------------------------
# USER: their util-iso.sh ends with `sudo chown $USER $outFolder`; in the
# container's non-login root shell $USER is unset and the chown (after the
# ISO is fully written) errors out the whole script.
export USER=root
# Their post-build rename hardcodes the "cachyos" filename prefix in two
# places; with our iso_name=astroos the mv can't find its source.
sed -i 's|/cachyos-$(date|/astroos-$(date|' "$base/util-iso.sh"
sed -i 's|vars+=("cachyos")|vars+=("astroos")|' "$base/util-iso.sh"
cd "$base"
./buildiso.sh -p desktop

# --- Collect artifacts ----------------------------------------------------
iso=$(find "$base/out" -name '*.iso' -printf '%f\n' | head -1)
[[ -n "$iso" ]] || { echo "!! No ISO produced" >&2; exit 1; }
mv "$(find "$base/out" -name '*.iso' | head -1)" /build/out/
cp "$prof/packages_desktop.x86_64" /build/out/manifest.pkglist
echo ">> ISO: /build/out/$iso"
