#!/usr/bin/env bash
# Generate astroos-additions.x86_64 from the ordered meta/*.list files.
# Council R1: the generated list is never hand-edited; meta/ is source of truth.
# Since R1.2 the base package set comes from CachyOS-Live-ISO's
# packages_desktop.x86_64 — this file holds ONLY the AstroOS additions, and the
# build dedupes it against the base list at build time.
# AUR packages (meta/aur.list) are intentionally EXCLUDED here — they are
# installed by a separate chroot AUR bootstrap, not by mkarchiso's pacman pass.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
meta="$here/meta"
out="$here/astroos-additions.x86_64"

# Ordered buckets. aur.list deliberately omitted.
order=(astroos-core astroos-astro astroos-continuity astroos-hacking astroos-research)

{
  echo "# GENERATED by scripts/gen-packages.sh — do not edit by hand."
  echo "# Source of truth: astroos/meta/*.list  (regenerate after editing those)."
  echo "# Generated from: ${order[*]}"
  echo
  for name in "${order[@]}"; do
    f="$meta/$name.list"
    [[ -f "$f" ]] || { echo "MISSING meta list: $f" >&2; exit 1; }
    grep -vE '^\s*(#|$)' "$f" | sed 's/[[:space:]]*#.*$//' | sed 's/[[:space:]]*$//' \
      | sed "s|^|${name}\t|"
  done
} > /tmp/astroos-pkgs.raw

# Dedupe by package name, keeping the first bucket that declared it.
# Provenance goes in section-header comment LINES, never inline (mkarchiso
# strips '#'-comments but not trailing whitespace).
{
  head -4 /tmp/astroos-pkgs.raw 2>/dev/null || true
  awk -F'\t' '!seen[$2]++ { if ($1 != cur) { cur = $1; printf "\n# --- %s ---\n", cur } print $2 }' \
    <(grep -P '\t' /tmp/astroos-pkgs.raw)
} > "$out"

count=$(grep -cvE '^\s*(#|$)' "$out" || true)
echo "Wrote $out ($count unique packages)."
