#!/usr/bin/env bash
# Generate astroos-additions.x86_64 from the ordered meta/*.list files.
# Council R1: the generated list is never hand-edited; meta/ is source of truth.
# Since R1.2 the base package set comes from CachyOS-Live-ISO's
# packages_desktop.x86_64 — this file holds ONLY the AstroOS additions, and the
# build dedupes it against the base list at build time.
# AUR packages (meta/aur.list) are intentionally EXCLUDED here: they ship as
# prebuilt signed binaries from the [astroos] repo (council R3) and are
# appended by container-build.sh when ASTROOS_WITH_AUR_REPO=1.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
meta="$here/meta"
out="$here/astroos-additions.x86_64"
raw="$(mktemp)"
trap 'rm -f "$raw"' EXIT

# Ordered buckets. aur.list deliberately omitted.
order=(astroos-core astroos-astro astroos-continuity astroos-hacking astroos-research astroos-laptop)

{
  echo "# GENERATED by scripts/gen-packages.sh — do not edit by hand."
  echo "# Source of truth: astroos/meta/*.list  (regenerate after editing those)."
  echo "# Generated from: ${order[*]}"
  echo
  for name in "${order[@]}"; do
    f="$meta/$name.list"
    [[ -f "$f" ]] || { echo "MISSING meta list: $f" >&2; exit 1; }
    tr -d '\r' < "$f" | grep -vE '^\s*(#|$)' \
      | sed 's/[[:space:]]*#.*$//' | sed 's/[[:space:]]*$//' \
      | sed "s|^|${name}\t|"
  done
} > "$raw"

# Dedupe by package name, keeping the first bucket that declared it.
# Provenance goes in section-header comment LINES, never inline (mkarchiso
# strips '#'-comments but not trailing whitespace).
{
  head -4 "$raw" 2>/dev/null || true
  # NF==2 keeps only bucket<TAB>pkg lines (grep -P is unavailable on some
  # hosts' grep builds and fails silently — never use it here).
  awk -F'\t' 'NF==2 && !seen[$2]++ { if ($1 != cur) { cur = $1; printf "\n# --- %s ---\n", cur } print $2 }' \
    "$raw"
} > "$out"

count=$(grep -cvE '^\s*(#|$)' "$out" || true)
# A zero-package additions list means the generator broke, not that AstroOS
# has no additions; shipping it would build a base-only ISO that still passes
# the boot gate. Fail loudly instead.
if [[ "${count:-0}" -eq 0 ]]; then
  echo "!! gen-packages produced 0 packages — refusing to write an empty additions list." >&2
  rm -f "$out"
  exit 1
fi
echo "Wrote $out ($count unique packages)."
