#!/usr/bin/env bash
# Generate archiso packages.x86_64 from the ordered meta/*.list files.
# Ratified in council R1: packages.x86_64 is GENERATED, never hand-edited.
# AUR packages (meta/aur.list) are intentionally EXCLUDED here — they are
# installed by a separate chroot AUR bootstrap, not by mkarchiso's pacman pass.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
meta="$here/meta"
out="$here/packages.x86_64"

# Ordered: core first, then buckets. aur.list deliberately omitted.
order=(astroos-core astroos-astro astroos-continuity astroos-hacking astroos-research)

{
  echo "# GENERATED by scripts/gen-packages.sh — do not edit by hand."
  echo "# Source of truth: astroos/meta/*.list  (regenerate after editing those)."
  echo "# Generated from: ${order[*]}"
  echo
  for name in "${order[@]}"; do
    f="$meta/$name.list"
    [[ -f "$f" ]] || { echo "MISSING meta list: $f" >&2; exit 1; }
    # strip comments + blanks, tag provenance, collect
    grep -vE '^\s*(#|$)' "$f" | sed 's/[[:space:]]*#.*$//' | sed 's/[[:space:]]*$//' \
      | sed "s|^|${name}\t|"
  done
} > /tmp/astroos-pkgs.raw

# Dedupe by package name, keeping first bucket that declared it (as a comment).
{
  head -4 /tmp/astroos-pkgs.raw 2>/dev/null || true
  awk -F'\t' '!seen[$2]++ { printf "%-40s # %s\n", $2, $1 }' \
    <(grep -P '\t' /tmp/astroos-pkgs.raw)
} > "$out"

count=$(grep -cvE '^\s*(#|$)' "$out" || true)
echo "Wrote $out ($count unique packages)."
