/* === This file is part of Calamares - <https://calamares.io> ===
 *
 *   SPDX-FileCopyrightText: 2015 Teo Mrnjavac <teo@kde.org>
 *   SPDX-FileCopyrightText: 2018 Adriaan de Groot <groot@kde.org>
 *   SPDX-License-Identifier: GPL-3.0-or-later
 *
 *   AstroOS: the CachyOS slideshow structure with three PNG slides
 *   (generated by astroos/branding/assetgen.py; PNG avoids the JPEG XL
 *   image plugin dependency).
 *
 *   The slides are 16:9 and the slideshow area is wider than that, so
 *   PreserveAspectFit leaves a bar down each side. Calamares paints those
 *   bars white. Each slide therefore carries a Rectangle behind the image
 *   whose gradient is the one the artwork itself uses, top #04030b to
 *   bottom #0e0820, so the bars read as part of the picture at any window
 *   size (R4.4, seen during the 2026-09-06 install run).
 */

import QtQuick 2.15;
import calamares.slideshow 1.0;

Presentation
{
    id: presentation

    function nextSlide() {
        console.log("QML Component (default slideshow) Next slide");
        presentation.goToNextSlide();
    }

    Timer {
        id: advanceTimer
        interval: 20000
        running: presentation.activatedInCalamares
        repeat: true
        onTriggered: nextSlide()
    }

    Slide {
        anchors.fill: parent

        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0.0; color: "#04030b" }
                GradientStop { position: 1.0; color: "#0e0820" }
            }
        }

        Image {
            id: background1
            source: "slide1.png"
            anchors.fill: parent
            fillMode: Image.PreserveAspectFit
        }
    }

    Slide {
        anchors.fill: parent

        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0.0; color: "#04030b" }
                GradientStop { position: 1.0; color: "#0e0820" }
            }
        }

        Image {
            id: background2
            source: "slide2.png"
            anchors.fill: parent
            fillMode: Image.PreserveAspectFit
        }
    }

    Slide {
        anchors.fill: parent

        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0.0; color: "#04030b" }
                GradientStop { position: 1.0; color: "#0e0820" }
            }
        }

        Image {
            id: background3
            source: "slide3.png"
            anchors.fill: parent
            fillMode: Image.PreserveAspectFit
        }
    }

    // V2 API: called by Calamares when the slideshow is shown/hidden.
    function onActivate() {
        console.log("QML Component (default slideshow) activated");
        presentation.currentSlide = 0;
    }

    function onLeave() {
        console.log("QML Component (default slideshow) deactivated");
    }
}
